domain: main-apps.dev
s3:
  bucket: kldx-dev
  region: ap-southeast-1
image_host: https://kldx-dev.s3.amazonaws.com
ga_tracking_id:
facebook:
  app_id: '1220073008062103'
billplz:
  collections:
    url: https://billplz-staging.herokuapp.com/api/v3/collections
