domain: kldxteam.com
s3:
  bucket: kldx-prod
  region: ap-southeast-1
image_host: https://kldx-prod.s3.amazonaws.com
ga_tracking_id: UA-93230339-1
facebook:
  app_id: '2005969142963890'
billplz:
  collections:
    url: https://www.billplz.com/api/v3/collections
